# Generated by Django 4.1.5 on 2023-02-02 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('cpf', models.CharField(max_length=11, primary_key=True, serialize=False, unique=True, verbose_name='CPF')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('data_nascimento', models.DateField(verbose_name='Data de nascimento')),
                ('foto', models.BinaryField(verbose_name='Foto')),
            ],
        ),
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=50, verbose_name='Descrição')),
                ('data_aquisicao', models.DateField(verbose_name='Data de nascimento')),
            ],
        ),
        migrations.CreateModel(
            name='Modalidade',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('faixa_etaria', models.CharField(max_length=10, verbose_name='Faixa etária')),
            ],
        ),
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('valor', models.FloatField(verbose_name='Valor')),
            ],
        ),
        migrations.CreateModel(
            name='Profissional',
            fields=[
                ('cargo', models.CharField(max_length=30, verbose_name='Cargo')),
                ('foto', models.BinaryField(verbose_name='Foto')),
                ('cref', models.CharField(max_length=15, verbose_name='CREF')),
                ('cpf', models.CharField(max_length=11, primary_key=True, serialize=False, unique=True, verbose_name='CPF')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.IntegerField(verbose_name='Número')),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('fk_modalidade_codigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.modalidade', verbose_name='Modalidade')),
            ],
        ),
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('endereco', models.CharField(max_length=150, verbose_name='Endereço')),
            ],
        ),
        migrations.CreateModel(
            name='Utiliza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario_inicio', models.TimeField(verbose_name='Início')),
                ('horario_fim', models.TimeField(verbose_name='Fim')),
                ('dia_semana', models.CharField(max_length=10, verbose_name='Dias da semana')),
                ('fk_sala_codigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sala', verbose_name='Sala')),
                ('fk_turma_codigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.turma', verbose_name='Turma')),
            ],
        ),
        migrations.CreateModel(
            name='Trabalha_Em',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario_inicio', models.TimeField(verbose_name='Início')),
                ('horario_fim', models.TimeField(verbose_name='Fim')),
                ('dia_semana', models.CharField(max_length=10, verbose_name='Dias da semana')),
                ('fk_profissional_cpf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.profissional', verbose_name='Profissional')),
                ('fk_unidade_codigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.unidade', verbose_name='Unidade')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Exercicio',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('fk_equipamento_codigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.equipamento', verbose_name='Equipamento')),
            ],
        ),
        migrations.AddField(
            model_name='sala',
            name='fk_unidade_codigo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.unidade', verbose_name='Unidade'),
        ),
        migrations.CreateModel(
            name='Ficha_Treinamento',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('vencimento', models.DateField(verbose_name='Vencimento')),
                ('data_criacao', models.DateField(verbose_name='Data de criação')),
                ('fk_aluno_cpf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.aluno', verbose_name='Aluno')),
                ('fk_profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.profissional', verbose_name='Profissional')),
            ],
        ),
        migrations.CreateModel(
            name='Exercicio_Prescrito',
            fields=[
                ('num_repeticoes', models.IntegerField(verbose_name='Repetições')),
                ('num_series', models.IntegerField(verbose_name='Series')),
                ('tecnica', models.CharField(max_length=50, verbose_name='Técnica')),
                ('intervalo_descanso', models.IntegerField(verbose_name='Intervalo')),
                ('observacao', models.CharField(max_length=100, verbose_name='Observação')),
                ('ritmo', models.CharField(max_length=4, verbose_name='Ritmo')),
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('fk_tipo_exercicio_codigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tipo_exercicio', verbose_name='Exercício')),
            ],
        ),
        migrations.CreateModel(
            name='Esta_Matriculado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_aluno_cpf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.aluno', verbose_name='Aluno')),
                ('fk_turma_codigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.turma', verbose_name='Turma')),
            ],
        ),
        migrations.AddField(
            model_name='equipamento',
            name='fk_sala_codigo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sala', verbose_name='Sala'),
        ),
        migrations.CreateModel(
            name='E_Composta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_exercicio_prescrito_codigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.exercicio_prescrito', verbose_name='Exercício prescrito')),
                ('fk_ficha_treinamento_codigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ficha_treinamento', verbose_name='Ficha de treinamento')),
            ],
        ),
        migrations.CreateModel(
            name='Da_Acesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_plano_codigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.plano', verbose_name='Plano')),
                ('fk_unidade_codigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.unidade', verbose_name='Unidade')),
            ],
        ),
        migrations.CreateModel(
            name='Conduz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_profissional_cpf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.profissional', verbose_name='Profissional')),
                ('fk_turma_codigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.turma', verbose_name='Turma')),
            ],
        ),
        migrations.CreateModel(
            name='Compreende',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_modalidade_codigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.modalidade', verbose_name='Modalidade')),
                ('fk_plano_codigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.plano', verbose_name='Plano')),
            ],
        ),
        migrations.AddField(
            model_name='aluno',
            name='fk_plano_codigo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.plano', verbose_name='Plano'),
        ),
    ]
