# Generated by Django 4.1.5 on 2023-02-01 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modalidade',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('faixa_etaria', models.CharField(max_length=10, verbose_name='Faixa etária')),
            ],
        ),
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('valor', models.FloatField(verbose_name='Valor')),
            ],
        ),
    ]
